# Generated by Django 5.2.8 on 2025-12-15 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_alter_invoice_invoice_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='shipment_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
