# Generated by Django 5.2.8 on 2025-12-15 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0007_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('DELIVERED', 'Delievered'), ('IN_PROGRESS', 'In Progress'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=200),
        ),
    ]
